Implemented HW2
ValeriaHil/Android pull request #1
Opened 2019-01-14 21:09 UTC by ValeriaHil

2019-01-15 18:56 UTC, lapenok-aleksej commented
файлы из папки .gradle не должны быть в репозитории

2019-01-15 19:13 UTC, aleksej-lapenok requested changes

2019-01-15 19:13 UTC, aleksej-lapenok commented on PictureList/app/app.iml
> +<?xml version="1.0" encoding="UTF-8"?>
файлы идеи тоже не должны быть здесь

2019-01-15 19:13 UTC, aleksej-lapenok commented on PictureList/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.WRITE_INTERNAL_STORAGE"/>
зачем?
если даже используешь где-то, то приложение будет падать (нет запроса в рантайме)

2019-01-15 19:13 UTC, aleksej-lapenok commented on PictureList/app/src/main/java/com/example/lenovo/hw2/Loader.kt
> +//    private fun deliver(id: Int, data: ByteArray) {
код в комментариях - ужасно

2019-01-15 19:13 UTC, lapenok-aleksej commented on PictureList/app/src/main/java/com/example/lenovo/hw2/PictureDetailFragment.kt
> +            ContextCompat.checkSelfPermission(this.context!!, "INTERNET")
зачем? 
1) context!! не безопасно
2) метод просто проверяет полученность пермишена и возвращает PERMISSION_GRANTED или PERMISSION_DENIED или PERMISSION_DENIED_APP_OP, а результат тут игнорируется
3) если указан пермишен на интернет, то он уже выдан и не надо его проверять

2019-01-15 19:13 UTC, lapenok-aleksej commented on PictureList/app/src/main/java/com/example/lenovo/hw2/PictureListActivity.kt
> +            ContextCompat.checkSelfPermission(parentActivity, "INTERNET")
зачем? (х2)

2019-01-15 19:13 UTC, lapenok-aleksej commented on PictureList/app/src/main/java/com/example/lenovo/hw2/pictures/PicturesContent.kt
> +        private val logTag = "ASYNC_TASK"
обычно делают константой статической

2019-01-15 19:13 UTC, lapenok-aleksej commented on PictureList/local.properties
> +## This file is automatically generated by Android Studio.
этого файла тоже не должно быть на гите

2019-01-15 19:22 UTC, lapenok-aleksej commented on PictureList/app/src/main/java/com/example/lenovo/hw2/PictureListActivity.kt
> +                val item = v.tag as PicturesContent.PictureItem
можно навесить OnClickListener в onBind

2019-01-15 19:23 UTC, aleksej-lapenok commented on PictureList/app/src/main/java/com/example/lenovo/hw2/pictures/PicturesContent.kt
> +    private val COUNT = 15
магическая переменная

2019-01-15 19:24 UTC, lapenok-aleksej commented on PictureList/app/src/main/java/com/example/lenovo/hw2/pictures/PicturesContent.kt
> +            ITEM_MAP.put(description, PictureItem(description, download, preview))
копипаста метода addItem

2019-01-16 11:14 UTC, ValeriaHil commented on PictureList/app/src/main/java/com/example/lenovo/hw2/PictureDetailFragment.kt
> +            ContextCompat.checkSelfPermission(this.context!!, "INTERNET")
Так а говорили же, что пользователь может потом забрать разрешение на интернет в настройках приложения и когда хотим скачать, нужно убедиться, что оно всё ещё есть, что с этим делать?

2019-01-16 11:17 UTC, ValeriaHil commented on PictureList/app/src/main/java/com/example/lenovo/hw2/pictures/PicturesContent.kt
> +    private val COUNT = 15
Разрешили же не бесконечный список, а сколько мне элементов нужно? Разве мы не сами решаем?

2019-01-16 11:32 UTC, lapenok-aleksej commented on PictureList/app/src/main/java/com/example/lenovo/hw2/PictureDetailFragment.kt
> +            ContextCompat.checkSelfPermission(this.context!!, "INTERNET")
Пользователь может отобрать только пермишены, которые запрашиваются в рантайме, их и проверяют каждый раз
разрешение на доступ в интернет - в группе normal permissions (не надо запрашивать в рантайме)

Так же обрати внимание на второй пункт: ты получаешь информацию о доступе, но НЕ используешь ее

2019-01-16 16:14 UTC, lapenok-aleksej commented on PictureList/app/src/main/java/com/example/lenovo/hw2/pictures/PicturesContent.kt
> +    private val COUNT = 15
должно быть const вместо val

2019-01-20 19:37 UTC, aleksej-lapenok approved these changes

2019-03-17 12:44 UTC, merged